### ISSUE TITLE
2016 Ruby 中国统计问题，选项整理

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/2016.rubyconfchina.org#1]
### 工作方式
- [ ] 全职 Ruby 工程师
- [ ] 远程 Ruby 工作
- [ ] 兼职、外包 Ruby 项目
- [ ] 学生
- [ ] 其他

**Comment by huacnlee** [comment]
### 工作地点
- [ ] 北京
- [ ] 上海
- [ ] 杭州
- [ ] 深圳
- [ ] 广州
- [ ] 成都
- [ ] 西安
- [ ] 其他，请填写

**Comment by Justme0** [comment]
兼职
苏州
